
/* CONTEXT constants */
RAW("#define CONTEXT_ARM64   0x00400000L"),
RAW("#define CONTEXT_CONTROL (CONTEXT_ARM64 | 0x1L)"),
RAW("#define CONTEXT_INTEGER (CONTEXT_ARM64 | 0x2L)"),
RAW("#define CONTEXT_FLOATING_POINT  (CONTEXT_ARM64 | 0x4L)"),
RAW("#define CONTEXT_DEBUG_REGISTERS (CONTEXT_ARM64 | 0x8L)"),
RAW("#define CONTEXT_X18 (CONTEXT_ARM64 | 0x10L)"),
RAW("#define CONTEXT_FULL 0x00400007L"),

/* Define context constants for genincdata.c compilation */
#define CONTEXT_ARM64   0x00400000L
#define CONTEXT_CONTROL (CONTEXT_ARM64 | 0x1L)
#define CONTEXT_INTEGER (CONTEXT_ARM64 | 0x2L)
#define CONTEXT_FLOATING_POINT  (CONTEXT_ARM64 | 0x4L)
#define CONTEXT_DEBUG_REGISTERS (CONTEXT_ARM64 | 0x8L)
#define CONTEXT_X18 (CONTEXT_ARM64 | 0x10L)
#define CONTEXT_FULL (CONTEXT_CONTROL | CONTEXT_INTEGER | CONTEXT_FLOATING_POINT)

/* Stack sizes */
CONSTANTX(KERNEL_STACK_SIZE, 0x3000),
CONSTANTX(KERNEL_LARGE_STACK_SIZE, 0xf000),
CONSTANTX(KERNEL_LARGE_STACK_COMMIT, 0x3000),
CONSTANTX(DOUBLE_FAULT_STACK_SIZE, 0x8000),

/* Thread Structure Offsets */
CONSTANTX(THREAD_CONTEXT_FRAME, 0x1B8),
CONSTANTX(THREAD_CONTEXT_X19, 0x98),
CONSTANTX(THREAD_CONTEXT_X21, 0xA8),
CONSTANTX(THREAD_CONTEXT_X23, 0xB8),
CONSTANTX(THREAD_CONTEXT_X25, 0xC8),
CONSTANTX(THREAD_CONTEXT_X27, 0xD8),
CONSTANTX(THREAD_CONTEXT_X29, 0xE8),
CONSTANTX(THREAD_CONTEXT_SP, 0xF8),
CONSTANTX(THREAD_APCSTATE_PROCESS, 0x130),

/* Process Structure Offsets */
CONSTANTX(PROCESS_DIRECTORYTABLEBASE, 0x28),
